name = "imicroseq-dashboard"
main = "cf-worker/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "dashboard.imicroseq-dataportal.ca", zone_name = "imicroseq-dataportal.ca", custom_domain = true }
]

[assets]
directory = "./public"
binding = "ASSETS"